### PR TITLE
kill villager, didn't kill before

### PR DESCRIPTION
**Pull request by 12944qwerty**

### CODE REVIEW

**Comment by 12944qwerty** [comment]
also made it so that you get sent text if you don't have right item and right click villager

**Review by Blackoutburst — APPROVED** [review]

**Comment by Blackoutburst** [comment]
I was not expecting any PR on this project lmao, it's just a very small project I've made for a friend in a few days but it's cool to see someone interested on it

Thanks for fixing these small issues

**Comment by 12944qwerty** [comment]
Eh, a bunch of party gamers practice with both your plugins
Also, I'm making a multiplayer supported jigsaw rush using your plugin too

**Comment by Blackoutburst** [comment]
Oh that cool I didn't know that, good luck with the multiplayer support

**Pull request merged**
